### ISSUE TITLE
Base line model issue 

### ISSUE THREAD

**Issue by maodayezheng** [matpalm/snli_nn_tf#1]
Hello ! I am also trying to implement the base line RNN model (uni direction) for SNLI in tensorflow, I am just wondering, did you share the weight between premise and hypothesis encoder rnn ? Or you set different weight for different encoder rnn ?

**Comment by matpalm** [comment]
in this tf version they were shared https://github.com/matpalm/snli_nn_tf/blob/master/nn_baseline.py#L100

tried a lot more variants in my original theano version
https://github.com/matpalm/snli_nn
